AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "input.image.bucket"
      AccessControl: BucketOwnerFullControl
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref SNSTopic
            Event: "s3:ObjectCreated:*"
    DependsOn:
      - SNSTopicPolicy
      - SNSTopic

  TargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "target.image.bucket"
      AccessControl: BucketOwnerFullControl
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref SNSTopic2
            Event: "s3:ObjectCreated:*"
    DependsOn:
      - SNSTopicPolicy2
      - SNSTopic2

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "SQSLambda"
              - "Arn"
          Protocol: "sqs"
        - Endpoint:
            Fn::GetAtt:
              - "SQSRDS"
              - "Arn"
          Protocol: "sqs"
      TopicName: "NewImageUpload"

  SNSTopic2:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "SQSRDS"
              - "Arn"
          Protocol: "sqs"
      TopicName: "ImageMoved"

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: "sns:Publish"
            Resource: !Ref SNSTopic
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub arn:${AWS::Partition}:s3:::input.image.bucket
      Topics:
        - !Ref SNSTopic

  SNSTopicPolicy2:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: "sns:Publish"
            Resource: !Ref SNSTopic2
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub arn:${AWS::Partition}:s3:::target.image.bucket
      Topics:
        - !Ref SNSTopic2

  SQSLambda:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "SQSLambdaPool"
      VisibilityTimeout: 210
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "SQSLambdaDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 2

  SQSLambdaDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "SQSLambdaDeadLetterQueue"

  SQSRDS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "SQSRDSPool"
      VisibilityTimeout: 40
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "SQSRDSDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 2

  SQSRDSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "SQSRDSDeadLetterQueue"

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSLambda
        - !Ref SQSRDS
      PolicyDocument:
        Id: AllowIncomingAccess
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "sns.amazonaws.com"
            Action:
              - sqs:SendMessage
            Resource:
              Fn::GetAtt:
                - SQSLambda
                - Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - Ref: SNSTopic
          - Effect: Allow
            Principal:
              Service:
                - "sns.amazonaws.com"
            Action:
              - sqs:SendMessage
            Resource:
              Fn::GetAtt:
                - SQSRDS
                - Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - Ref: SNSTopic
                  - Ref: SNSTopic2
    DependsOn:
      - SQSLambda
      - SQSRDS
      - SNSTopic
      - SNSTopic2

  LambdaS3:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - LambdaRole
    Properties:
      FunctionName: "Lambda_S3_Copy_New_File"
      Handler: index.handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 120
      TracingConfig:
        Mode: Active
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib.parse

          print('Moving File')

          s3 = boto3.resource('s3')

          def handler(event, context):
              body = json.loads(event['Records'][0]['body'])
              message = json.loads(body['Message'])
              input_bucket = message['Records'][0]['s3']['bucket']['name']
              target_bucket = 'target.image.bucket'
              filename = urllib.parse.unquote_plus(message['Records'][0]['s3']['object']['key'], encoding='utf-8')
              try:
                copy_source = {
                    'Bucket': input_bucket,
                    'Key': filename
                }
                
                target_bucket = s3.Bucket(target_bucket)
                target_bucket.copy(copy_source, filename)
              except Exception as e:
                print(f'Failed to move file { filename } from { input_bucket } to { target_bucket }')
                print(e)
                raise e

  LambdaRDS:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - LambdaRole
      - PyMySQLLayer
    Properties:
      FunctionName: "Lambda_RDS_Add_New_File"
      Handler: index.handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 30
      TracingConfig:
        Mode: Active
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Layers:
        - !Ref PyMySQLLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet
      Code:
        ZipFile: |
          import urllib.parse
          import pymysql
          import sys

          print('Copying File')

          rds_host = 'srkkptctytdxvy.cbw7wafbrizg.eu-central-1.rds.amazonaws.com'
          name = 'admin'
          password = 'dbinstancetest2022'
          db_name = 'RDSImageDB'
          port = 3306

          try:
              conn = pymysql.connect(host=rds_host,user=name,
                                    passwd=password,db=db_name,
                                    connect_timeout=5,
                                    cursorclass=pymysql.cursors.DictCursor)
          except pymysql.MySQLError as e:
              print(e)
              sys.exit()


          def handler(event, context):
              body = json.loads(event['Records'][0]['body'])
              trigger = body['TopicArn']
              message = json.loads(body['Message'])
              bucket = message['Records'][0]['s3']['bucket']['name']
              filename = urllib.parse.unquote_plus(message['Records'][0]['s3']['object']['key'], encoding='utf-8')
              
              
              with conn.cursor() as cur:
                if 'NewImageUpload' in trigger:
                  cur.execute('SELECT EXISTS (SELECT ImageName FROM Images WHERE ImageName=%s)', filename)
                  exists = cur.fetchone()
                  exists = list(exists.values())[0]
                  
                  if exists == 1:
                    print (f'The file { filename } already exists in the database')
                    return 0
                    
                  cur.execute('INSERT INTO Images (ImageName, SourcePath, RetouchedPath) VALUES(%s, %s, %s)', (filename, bucket, 'default'))
                  conn.commit()
                    
                  print (f'Successfully added file { filename } to the database')
                  return 0
                    
                cur.execute('UPDATE Images SET RetouchedPath=%s WHERE ImageName=%s', (bucket, filename))
                conn.commit()
                print (f'Successfully update file { filename } entry in the database')
                return 0

  PyMySQLLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: python.layer.bucket
        S3Key: pymysql_layer.zip
      Description: PyMySQL Layer
      LayerName: PyMySQL_Layer
      LicenseInfo: MIT

  LambdaRole:
    Type: "AWS::IAM::Role"
    DependsOn:
      - SQSLambda
      - SQSRDS
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "lambda_allow_access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ec2:*
                Resource: "*"
              - Effect: Allow
                Action: eds:*
                Resource: "*"
              - Effect: Allow
                Action: s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - Fn::GetAtt:
                      - SQSLambda
                      - Arn
                  - Fn::GetAtt:
                      - SQSRDS
                      - Arn
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

  LambdaS3EventListener:
    Type: "AWS::Lambda::EventSourceMapping"
    DependsOn:
      - SQSLambda
      - LambdaS3
    Properties:
      BatchSize: 16
      FunctionResponseTypes:
        - ReportBatchItemFailures
      MaximumBatchingWindowInSeconds: 30
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
          - SQSLambda
          - Arn
      FunctionName:
        Fn::GetAtt:
          - LambdaS3
          - Arn

  LambdaRDSEventListener:
    Type: "AWS::Lambda::EventSourceMapping"
    DependsOn:
      - SQSRDS
      - LambdaRDS
    Properties:
      BatchSize: 4
      FunctionResponseTypes:
        - ReportBatchItemFailures
      MaximumBatchingWindowInSeconds: 30
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
          - SQSRDS
          - Arn
      FunctionName:
        Fn::GetAtt:
          - LambdaRDS
          - Arn

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: RDSImageDB
      MasterUsername: admin
      MasterUserPassword: "dbinstancetest2022"
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      PubliclyAccessible: true
      AllocatedStorage: "5"
      VPCSecurityGroups:
        - !Ref SecurityGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroup

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ]

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIPAddress.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub NAT-${AWS::StackName}

  ElasticIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: description
      SubnetIds:
        - !Ref PrivateSubnet
        - !Ref PublicSubnet
